name: List AWS S3 Bucket Objects

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  S3BucketIntegration:
    name: Deploy Site
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
 
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
  
      # List all buckets
      - name: List S3 Bucket
        run: |
          echo "==> Listing all S3 buckets"
          aws s3 ls

      - name: Upload the site contents
        run: |
          aws s3 cp README.md s3://anus3demo1/
